[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "bibtexparser"
description = "Bibtex parser for python 3"
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
license-files = ["LICENSE"]
authors = [{ name = "Michael Weiss and other contributors", email = "code@mweiss.ch" }]
maintainers = [{ name = "Michael Weiss", email = "code@mweiss.ch" }]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Operating System :: OS Independent",
]
dependencies = ["pylatexenc~=2.10"]
dynamic = ["version"]

[project.optional-dependencies]
test = [
    "pytest",        # Test runner
    "pytest-xdist",  # Parallel tests: `pytest -n <num-workers>`
    "pytest-cov",    # Code coverage
    "jupyter",       # For runnable examples
]
docs = ["sphinx"]

[project.urls]
Homepage = "https://github.com/sciunto-org/python-bibtexparser"
Repository = "https://github.com/sciunto-org/python-bibtexparser"

[tool.setuptools.packages.find]
include = ["bibtexparser", "bibtexparser.*"]

[tool.setuptools.package-data]
bibtexparser = ["py.typed"]

[tool.setuptools.dynamic]
version = { attr = "bibtexparser.__version__" }
