[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=77"]

[project]
authors = [{name = "Michael Weiss and other contributors", email = "code@mweiss.ch"}]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Text Processing :: Markup :: LaTeX",
    "Operating System :: OS Independent",
]
dependencies = ["pylatexenc~=2.10"]
description = "Bibtex parser for python 3"
dynamic = ["version"]
license = "MIT"
license-files = ["LICENSE"]
maintainers = [{name = "Michael Weiss", email = "code@mweiss.ch"}]
name = "bibtexparser"
readme = "README.md"
requires-python = ">=3.9"

[project.optional-dependencies]
docs = ["sphinx"]
test = [
    "pytest",  # Test runner
    "pytest-xdist",  # Parallel tests: `pytest -n <num-workers>`
    "pytest-cov",  # Code coverage
    "jupyter",  # For runnable examples
]

[project.urls]
Homepage = "https://github.com/sciunto-org/python-bibtexparser"
Repository = "https://github.com/sciunto-org/python-bibtexparser"

[tool.setuptools.dynamic]
version = {attr = "bibtexparser.__version__"}

[tool.setuptools.package-data]
bibtexparser = ["py.typed"]

[tool.setuptools.packages.find]
include = ["bibtexparser", "bibtexparser.*"]
